### ISSUE TITLE
Can't call update() when using CTE manager

### ISSUE THREAD

**Issue by kingbuzzman** [dimagi/django-cte#9]
```
>>> type(qs)
<class 'django_cte.cte.CTEQuerySet'>
>>> str(qs.query)
'SELECT * FROM model INNER JOIN model2 ON (model."obj_id" = "model2"."id") WHERE ( "model"."id" IN (1, 2, 3, 5, 11, 100)) ORDER BY "notification_inbox"."sent_timestamp" DESC'
>>> qs.update(field1='Hello')
*** django.db.utils.ProgrammingError: syntax error at or near ")"
LINE 1: ... SET "field1" = 'Hello' WHERE "model"."id" IN ()
```

Looking at the postgres logs, im able to see that the query being ran is: `UPDATE "model" SET "field1" = 'Hello' WHERE "model"."id" IN ()`

If i swap out the `objects = CTEManager()` for a `objects = models.Manager()` everything works as expected.

As a temporary solution ive keep the `objects = models.Manager()` and added a `cte_objects = CTEManager()` -- while not ideal, it works.

**Comment by ryanhiebert** [comment]
I'm seeing this issue or a variant of it, but I've needed to use the CTEQuerySet, so using the regular manager wasn't really an option, but I was able to do what I needed in my case by updating directly with filtering only on the ids from `values_list`.

**Comment by Azd325** [comment]
I'm running also in this issue.

**Comment by timworx** [comment]
I'm running into this issue currently. 

I can't replace the `objects` manager without this blowing up other parts of the app that use `.update` on the queryset.

I _think_ it's winding up on the query here: https://github.com/django/django/blob/main/django/db/models/sql/compiler.py#L1646

**Comment by jnns** [comment]
After making the test suite run in pytest instead of nose (https://github.com/dimagi/django-cte/pull/63), I wrote the following test to reproduce the behaviour of this issue:

```python
@pytest.mark.skipif(
    connection.vendor == "sqlite",
    reason="SQLite doesn't fail on 'WHERE field IN ()'"
)
def test_regular_update_query(self):
    """Regression test for https://github.com/dimagi/django-cte/issues/9"""
    Order.objects.filter(region="mars").update(amount=100)  # Works.
    Order.objects.filter(region__parent="mars").update(amount=100)  # Doesn't work.

```

While the first queryset correctly produces the following query …
```sql
UPDATE "orders" SET "amount" = 100 WHERE "orders"."region_id" = 'mars'
```
… the latter results in:

```sql
UPDATE "orders" SET "amount" = %s WHERE "orders"."id" IN ()
```

I tried to pinpoint the issue and ended up with the same discoveries as @timworx: `CTEQueryUpdateCompiler.pre_sql_setup()` has a `WHERE` clause like this 

```python
<WhereNode: (AND: RelatedExact(Col(U1, tests.Region.parent), 'mars'))>
``` 
until [`self.query.clear_where()`](https://github.com/django/django/blob/9c42933711667034c9335f408e1a8a53031e9865/django/db/models/sql/compiler.py#L1987) is called. It is then rebuilt with the broken WHERE clause when [`self.query.add_filter("pk__in", query)`](https://github.com/django/django/blob/9c42933711667034c9335f408e1a8a53031e9865/django/db/models/sql/compiler.py#L2002) is called:

```python
<WhereNode: (AND: In(Col(U0, tests.Order.id), <django_cte.query.CTEUpdateQuery object at 0x7ff13e3e9e10>))>
```

**Comment by millerdev** [comment]
Fixed by https://github.com/dimagi/django-cte/pull/71
